<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Gldq;
use AppBundle\Implement\GpImplement;

/**
 * GldqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GldqRepository extends GpImplement
{

}