<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Zbgf;
use AppBundle\Implement\GpImplement;

/**
 * ZbgfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZbgfRepository extends GpImplement
{

}